### ISSUE TITLE
Not receiving contacts in pidgin

### ISSUE THREAD

**Issue by ducklin5** [davidgfnet/whatsapp-purple#159] opened 2014-08-31 10:44 UTC
i was supposed to have received some contacts from a friend but i never got them, i waited but it didn't show up. my friend confirm it was sent with "the 2 ticks". any help

**Comment by davidgfnet** [comment] 2015-02-26 18:41
This is a duplicate of #92. Thanks for reporting

**Closed by davidgfnet** 2015-02-26 18:41 UTC
Labels: bug
