### ISSUE TITLE
I can't recive text messages from contacts but groups

### ISSUE THREAD

**Issue by tomascastana** [davidgfnet/whatsapp-purple#216] opened 2015-02-06 01:05 UTC
Hi! Since some days i can't recive text message from any contact. They send me and inmediatly double blue check is present in them whatsapp, but nothing is recieved in my pidgin.
If they send me an audio or a picture, it's recieved. Or if they text me from a group, too is recieved.
I was using the last-whatsapp.dll (very old), so i compiled a new from the last commit (0.7) and the same. I tested in another pc, with another pidgin and the same. Everytime under windows.

Important! Two days ago, i use my whatsapp from an android emulator (sdk), I installed whatsapp and registered again. Everything okay. I tested web whatsapp and okay too. I extracted the pw and I return to the pidgin.
At this moment, i can't remember if that problem already was present, but i think that yes, because i was talking through groups.

I don't write this for a solution, else for share my experience if somebody decided to try whatsapp web and found with the same problem.

Thanks

**Comment by dequis** [comment] 2015-02-06 01:38
Are you running the android emulator at the same time as whatsapp-purple? In that case, that one is eating the messages.

Whatsapp doesn't support more than one client at the same time - whatsapp web doesn't count, since they made it so that it talks to the phone instead of talking to whatsapp's servers, but you can't have both whatsapp-purple **and** the android client.

So choose either whatsapp android + whatsapp web **or** whatsapp-purple. If you still keep losing messages after stopping using either of those, re-register the number.

**Comment by tomascastana** [comment] 2015-02-06 01:56
Yes, i known that since i tried to use 2 sessions of pidgin at the same time. Actually, i don't use an emulator, i boot from a live android x86 iso on a notebook, so, i used whatsapp, exctracted the pw and turn off the os. After, i use pidgin with the pw and i have this problem. Then i proced to re-register my number with WART, and the problem continues.

I'm don't know the api, how it works internally. I disknow any debug process that i can do. If there are something, tell me that i test it.

Thanks.

**Comment by davidgfnet** [comment] 2015-02-06 09:38
Hey Tomacastaña!
Might it be because Android is using ciphered messages? Just guessing.
It would be very interesting to know a couple of things:
1- How did you extract your pw from the android machine? I'd need to do that.
2- Send a trace to me so I can debug it. To do so you'll need to capture a trace with Wireshark and give me your password so I can decrypt it. If you need more help in this contact me at david at davidgf dot net
Thanks!

**Comment by tomascastana** [comment] 2015-02-06 17:31
Hablo en castellano pero no soy español! Je Tomás Castana (without ñ)
I extracted the pw with this apk https://github.com/mgp25/WhatsAPI-Official/wiki/Extracting-password-from-device#using-apk and root privileges.
Regarding the trace, where can i find the process to decrypt the Wireshark Trace, and what packets need in the trace (what i have to do, to send with whatsapp).

Thanks!!

**Comment by tomascastana** [comment] 2015-02-06 17:39
I saw your's wireshark-whatsapp repo. Tell me what packets needs.

**Comment by davidgfnet** [comment] 2015-02-06 19:14
Hey. You don't need the wireshark-whatsapp at all. I'm the one who needs it.
So just open wireshark start capturing traffic (you'd better close torrentz and alike) and try to reproduce the bug. Thanks!

**Comment by tomascastana** [comment] 2015-02-06 19:23
But... i prefer send you the packets already decrypted... jeje I will boot in linux and contact you. Surely will be by email.

**Comment by maicomstoppa** [comment] 2015-02-11 16:38
Any news about this issue?
I'm experimenting the same behavior (Pidgin Windows here). 

Phone is at "plane mode", so, no MPOP running right now. 
Still, only groups appear on my Pidgin list.

Thanks.

**Comment by davidgfnet** [comment] 2015-02-11 17:11
Could you send a trace? A wireshark trace I mean.
I can send you a debug version so you can get a dump and send it back to
me. That could help a lot.

**Comment by tomascastana** [comment] 2015-02-11 18:37
Sorry the time. I start to work and don't have so much time to take a trace with wireshark. I couldn't install whatsapp-wireshark at linux, jeje. From one moment to another i can chat normally with a contact (that i can't chat with him previously). There are a contact that i can not chat yet. I will take a trace when i get to chat with him. I know this can be useful.

En español: Tardo en escribir en inglés y creo que vos david entendes un poco de español (si es que no es tu lengua nativa). Tengo que coordinar con ese contacto que todavía no puedo establecer comunicación para que me envíe algún mensaje mientras esté capturando el tráfico. No es mi mamá o un hermano donde yo pueda tener su celular en la mano y hacer pruebas libremente.

Avisaré!

Gracias!!!

**Comment by maicomstoppa** [comment] 2015-02-12 10:43
Hi, David.

The thing is: I'm stupid.

After trying to dis/connect, remove/insert the account, I've realized that my chat with contacts was working. All I needed was to add them manually, what make sense, since Whatsapp uses Android's contact list (in my case) to make the magic happen.

**Comment by davidgfnet** [comment] 2015-02-12 10:47
Now that makes sense. You were the only one having that issue, which was kind of suspicious...
Let me close this then!

**Closed by davidgfnet** 2015-02-12 10:47 UTC
