### ISSUE TITLE
error connectiong, not authorized

### ISSUE THREAD

**Issue by mcirsta** [davidgfnet/whatsapp-purple#271] opened 2015-05-20 22:13 UTC
Everything was working fine but I'm suddenly getting this error:

01:11:28) dns: Successfully sent DNS request to child 21535
(01:11:28) dns: Got response for 'c2.whatsapp.net'
(01:11:28) dnsquery: IP resolved for c2.whatsapp.net
(01:11:28) proxy: Attempting connection to 173.192.222.169
(01:11:28) proxy: Connecting to c2.whatsapp.net:443 with no proxy
(01:11:28) proxy: Connection in progress
(01:11:28) proxy: Connecting to c2.whatsapp.net:443.
(01:11:28) proxy: Connected to c2.whatsapp.net:443.
(01:11:29) util: Writing file accounts.xml to directory /home/marius/.purple
(01:11:29) util: Writing file /home/marius/.purple/accounts.xml
(01:11:30) connection: Connection error on 0x1764270 (reason: 2 description: not-authorized)

 I'm not sure if it's only me or they've change something at whatsapp to block 3rd party clients.

**Comment by dequis** [comment] 2015-05-21 03:38
Re-register that number. If it says you're blocked, you're blocked, if not, you'll get a new password

**Comment by mcirsta** [comment] 2015-05-21 11:28
Yeah I'm blocked ... oh well , I can use a new number I guess ... problem is many more people can get blocked if they've found a way of detecting users of this.

**Comment by Yaco** [comment] 2015-05-25 19:40
I had the same problem. I registered a new number as usual. After less than 5 minutes my user was blocked. I think WhatsApp is actively blocking 3rd party clients. Are we lost?

**Comment by mcirsta** [comment] 2015-05-25 20:17
I think the problem is they managed to detect the usage of this client. It could be the string being used when connecting or just some specific behaviour of whatsapp-purple.

 All's not lost but it seems modifications are needed to emulate the original client better. I did some reversing on the whatsapp Android client but then I found this...

**Comment by davidgfnet** [comment] 2015-05-25 20:50
Feel free to send pull requests! In my case I've been using it for years with different numbers and never had a problem...

**Comment by robercal** [comment] 2015-05-26 09:15
Same problem here, resource string being used was: Android-2.31.151-443 on linux x86.

**Comment by nathandh** [comment] 2015-05-26 18:15
I use the default_resource defined in ```wa_purple.c``` (currently Android-2.12.5-443) and haven't a problem. But, I have a pc dedicated whatsapp account that I use when using whatsapp-purple. I also maintain a separate whatsapp account that exists solely on my android device. I think those experiencing problems are trying to log on from their phone, and also from their desktop/laptop computer with the same whatsapp account.... resulting in a ban.

**Comment by Yaco** [comment] 2015-05-26 18:17
That's not my case. I don't have a smartphone, I only connect using pidgin. I am using ```Android-2.31.151-443```

**Comment by davidgfnet** [comment] 2015-05-26 18:18
Thanks for the clarification @nathandh. I'm pretty sure that using an account on both PC and cellphone will result in a quick ban. If that's the case, guys, use whatsapp web. It's free and easy to use!
I am closing this issue, since I think it has lots of useful information.

**Closed by davidgfnet** 2015-05-26 18:18 UTC

**Comment by Yaco** [comment] 2015-05-26 18:22
Why did you close it? The issue is not solved. As I said, I was banned twice using only whatsapp-purple. Please re-open it.

**Comment by davidgfnet** [comment] 2015-05-26 18:33
Hey Yaco. There is no solution for this issue. Only improving the plugin will reduce the number of bans. Just in case some of you don't read the whatsapp ToS, using this plugin violates the ToS :)

**Comment by mcirsta** [comment] 2015-05-26 20:54
Turns out I was using a WP7 resource, maybe that was the problem, not sure. I won't be using this on the phone so let's see.
 Also maybe keeping this open helps to reduce the number of dups ... I only opened it because I thought everyone is getting banned.

**Comment by githubtefo** [comment] 2015-05-27 17:51
I just received the "not authorized" sentence.
I'm wondering where is the XMPP implementation...
WhatsApp/facebook should give us some flexibility, since they have no support for many platforms, like FirefoxOS and Desktop environments.
Sorry david, I know that it's not the space for this topic, but Im so furious and frustated.

**Comment by davidgfnet** [comment] 2015-05-27 17:58
I understand. And thats why we should care about open standards and open source. Everybody forgets about that when things "just work", but when we come into trouble we should realize it's all our (the clients) fault.

**Comment by githubtefo** [comment] 2015-05-28 00:01
@davidgfnet this is not YOUR fault, you are part of the solution. And thank you for that.

**Comment by buguelos** [comment] 2015-07-28 15:08
just change string for android version for new one! bcz new version of whatsapp doesn’t support old android software version! as you can see  Android-2.31.151-443 it's very old one so than they can easily find out you are not official client! i had about 20 whatsapp blocked till i debug and found out that the string android was so old and with you use more than one account must use proxy for every one recommencement sock 4 transparent

**Comment by buguelos** [comment] 2015-07-28 15:11
android string Android-5.21.1

**Comment by mcirsta** [comment] 2015-07-28 15:54
Maybe make this default in a new version ? You can't really expect (all) users to set this.
